platform :ios, '9.0'

target 'FlowerJeonjuTrip' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlowerJeonjuTrip

  pod 'Alamofire', '~> 4.4'
  pod 'SwiftyJSON'
  pod 'SWXMLHash', '~> 4.0.0'
  pod 'Kingfisher', '~> 4.0'
  pod 'Toaster'

end
